CREATE TABLE paperdolls (
  character_id INT NOT NULL PRIMARY KEY,
  boots INT NOT NULL DEFAULT 0,
  accessory INT NOT NULL DEFAULT 0,
  gloves INT NOT NULL DEFAULT 0,
  belt INT NOT NULL DEFAULT 0,
  armor INT NOT NULL DEFAULT 0,
  necklace INT NOT NULL DEFAULT 0,
  hat INT NOT NULL DEFAULT 0,
  shield INT NOT NULL DEFAULT 0,
  weapon INT NOT NULL DEFAULT 0,
  ring INT NOT NULL DEFAULT 0,
  ring2 INT NOT NULL DEFAULT 0,
  armlet INT NOT NULL DEFAULT 0,
  armlet2 INT NOT NULL DEFAULT 0,
  bracer INT NOT NULL DEFAULT 0,
  bracer2 INT NOT NULL DEFAULT 0
);