CREATE TABLE positions (
  character_id INT NOT NULL PRIMARY KEY,
  map INT NOT NULL DEFAULT 192,
  x INT NOT NULL DEFAULT 7,
  y INT NOT NULL DEFAULT 6,
  direction INT NOT NULL DEFAULT 2,
  sitting INT NOT NULL DEFAULT 0,
  `hidden` INT NOT NULL DEFAULT 0
);