SELECT c.account_id,
       c.name,
    	 c.title,
       c.home,
       c.fiance,
       c.partner,
       c.admin_level,
       c.class,
       c.gender,
       c.race,
       c.hair_style,
       c.hair_color,
       c.bank_level,
       c.gold_bank,
       c.guild_rank,
       c.guild_rank_string,
       c.boots,
       c.accessory,
       c.gloves,
       c.belt,
       c.armor,
       c.hat,
       c.shield,
       c.weapon,
       c.ring,
       c.ring2,
       c.armlet,
       c.armlet2,
       c.bracer,
       c.bracer2,
       c.necklace,
       c.level,
       c.experience,
       c.hp,
       c.tp,
       c.strength,
       c.intelligence,
       c.wisdom,
       c.agility,
       c.constitution,
       c.charisma,
       c.stat_points,
       c.skill_points,
       c.karma,
       c.usage,
       c.map,
       c.x,
       c.y,
       c.direction,
       c.sitting,
       c.hidden,
       g.name,
       g.tag
FROM `characters` c
LEFT JOIN `guilds` g
	ON g.id = c.guild_id
WHERE c.id = :character_id;
